"""add_tipo_to_categorias

Revision ID: f3681b2b991f
Revises: ffc5959df786
Create Date: 2026-06-27 23:42:40.174780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3681b2b991f'
down_revision: Union[str, Sequence[str], None] = 'ffc5959df786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('tipo', sa.Enum('gasto', 'recebimento', name='tipocategoria'), nullable=False, server_default='gasto'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categorias', 'tipo')
    # ### end Alembic commands ###
